# Generated by Django 2.2 on 2023-06-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20230625_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlist',
            name='zipcode',
            field=models.IntegerField(default=1, max_length=5, verbose_name='zipcode'),
            preserve_default=False,
        ),
    ]
