# Generated by Django 2.2 on 2023-06-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartlist_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartlist',
            name='zipcode',
        ),
    ]
