# Generated by Django 2.2 on 2023-07-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartlist_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='cart_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cartlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
