# Generated by Django 2.2 on 2023-08-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230315_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(height_field=400, upload_to='products', width_field=500),
        ),
    ]
