# Generated by Django 2.2 on 2023-11-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20231106_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='UserProfile',
        ),
    ]
